= {lab_name}

== 1. Introduction and Overview - 10 minutes

**Welcome to our workshop!**

This lab will give attendees a comprehensive understanding of OpenShift as an application platform that can accelerate their day-to-day activities, from modernization to adopting DevSecOps combined with a GitOps approach to running applications in hybrid cloud environments to the edge.


After completing the lab, you should feel comfortable speaking with customer application and developer teams about the benefits of using OpenShift as the application platform they need to build, deploy, manage, and auto-scale their applications with serverless.

== 2. Modules Overview

This lab consists of 3 modules to enable you with hands-on to try solutions connected with the application platform story.

* Developer Experience & Application Modernization (30 mins)

** Explore developer experience to understand developers' journeys to modernize and build applications. This module will show how the OpenShift Application Platform brings developer productivity by reducing complexity and overhead from operations. 

* Extend to the edge and interconnect (20 mins)

** Extend Red Hat to the Edge to run workloads anywhere and connect easily with Red Hat Service Interconnect in hybrid cloud environments and at the edge.

* Security and Automation in Software Delivery (30 mins)

This section will showcase how OpenShift Platform Plus (OPP) can provide a comprehensive DevSecOps workflow, focusing on Software Supply Chain Security throughout the entire process, from development to production. DevSecOps stands for Development, Security, and Operations and is a holistic approach that promotes continuous security within your DevOps practices.




