kind: Service
apiVersion: v1
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    deployment: inventory
metadata:
  name: inventory
  labels:
    app: inventory
  annotations:
    description: The web server's http port
